service:
  port: 9090
logging:
  verbose: false
oauth:
  keycloak:
    base: http://oauth:8080
    realm: c2ng
    retry-timeout: 5
uss:
  endpoint: http://uss:9091
  oauth:
    keycloak:
      base: http://oauth:8080
      realm: c2ng
      auth-client-id: uss-access
mongo:
  uri: mongodb://root:example@mongo:27017/
nsacf:
  simulated: true
  uri: https://host:port/
security:
  certificate: /c2ng/config/service.pem
  private: /c2ng/config/private.pem
  default-ttl: 3600
influx:
  uri: http://influxdb:8086
  org: c2ng
  bucket: aerial-data
