openapi: 3.0.3
info:
  version: 0.1.0
  title: Flyvercity C2NG Service Customer Protocol
paths:
  /uav/session:
    post:
      summary: Aerial Connectivity Session Request for UAV
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ReferenceTime:
                  description: Reference time in UTC
                  type: string
                  format: date-time
                UavID:
                  description: UAV identifier as registered with the Service
                Waypoints:
                  type: array
                  description: Flight waypoint hints
                  items:
                    $ref: '#/components/schemas/GeoPoint'
                OperationalMargin:
                  type: number
                  format: double
                  description: Lateral safety margin in meters
                UssMetadata:
                  type: object
      responses:
        '200':
          description: Session Response to UAV
          content:
            application/json:
              schema:
                type: object
                properties:
                  Success:
                    type: boolean
                  IP:
                    type: string
                  Gateway:
                    type: string
                  SessionSecret:
                    type: string
                    format: byte
        '400':
          description: Wrong request response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
  /rps/session:
    get:
      summary: Get RPS public key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                UavID:
                  type: string
      responses:
        '200':
          description: Returning public key for the associated RPS
          content:
            application/json:
              schema:
                type: object
                properties:
                  SessionPublic:
                    type: string
                    format: byte
        '400':
          description: Wrong request response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
    post:
      summary: Aerial Connectivity Session Request for RPS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - ReferenceTime
                - RpsID
                - UavIDs
              properties:
                ReferenceTime:
                  description: Reference time in UTC
                  type: string
                  format: date-time
                RpsID:
                  description: RPS identifier as registered with the Service
                  type: string
                UavIDList:
                  description: A list of UAV identifiers that the RPS intends to control
                  type: array
                  items:
                    type: string
                Position:
                  description: RPS Location
                  $ref: '#/components/schemas/GeoPoint'
      responses:
        '200':
          description: Response to UAM
          content:
            application/json:
              schema:
                type: object
                properties:
                  Success:
                    type: boolean
                  IP:
                    type: string
                  Gateway:
                    type: string
                  SessionSecret:
                    type: string
                    format: byte
                  UavCredentials:
                    type: array
                    items:
                      type: object
                      properties:
                        ID:
                          type: string
                        IP:
                          type: string
                        SessionPublic:
                          type: string
                          format: byte
        '400':
          description: Wrong request response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
components:
  schemas:
    GeoPoint:
      type: object
      properties:
        Latitude:
          description: WGS-84 latitude (in degrees, negative value indicates Southern Hemisphere)
          type: number
          format: double
        Longitude:
          description: WGS-84 longitude (in degrees, negative value indicates Western Hemisphere)
          type: number
          format: double
        Altitude:
          description: Height above WGS-84 ellipsoid in meters
          type: number
          format: double
    BadRequestResponse:
      type: object
      properties:
        Success:
          type: boolean
        ErrorID:
          type: string
        ErrorString:
          type: string
