version: '3'

services:
  oauth:
    image: quay.io/keycloak/keycloak
    restart: unless-stopped
    env_file:
      - .env
    command: [ 'start-dev' ]
    ports:
      - 8080:8080
    networks:
      - c2ng

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    networks:
      - c2ng

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    networks:
      - c2ng
    depends_on:
      - mongo

  influxdb:
    image: influxdb
    env_file:
      - .env
    volumes:
      - influx:/var/lib/influxdb2
    ports:
      - 8086:8086
    networks:
      - c2ng

  influxdb_cli:
    image: influxdb
    links:
      - influxdb
    env_file:
      - .env
    volumes:
      - influx:/var/lib/influxdb2
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    depends_on:
      - influxdb

  c2ng:
    image: c2ng
    env_file:
      - .env
    volumes:
      - ./service:/c2ng/service
      - ./config/c2ng/:/c2ng/config/
    ports:
      - 9090:9090
    networks:
      - c2ng
    depends_on:
      - mongo

networks:
  c2ng:

volumes:
  influx:
