version: '3'

services:
  oauth:
    image: quay.io/keycloak/keycloak
    restart: unless-stopped
    env_file:
      - .env
    command: [ 'start-dev' ]
    ports:
      - 8080:8080
    networks:
      - c2ng

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file:
      - .env
    networks:
      - c2ng

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - .env
    networks:
      - c2ng
    depends_on:
      - mongo

  influxdb:
    image: influxdb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - influx:/var/lib/influxdb2
    ports:
      - 8086:8086
    networks:
      - c2ng

  uss:
    image: c2ng-uss-sim
    env_file:
      - .env
    volumes:
      - ./c2ng/uss_sim:/app/c2ng/uss_sim
    ports:
      - 9091:9091
    networks:
      - c2ng

  c2ng:
    image: c2ng
    env_file:
      - .env
    volumes:
      - ./c2ng/common:/app/c2ng/common
      - ./c2ng/service:/app/c2ng/service
      - ./docker/core/config:/app/config
    ports:
      - 9090:9090
    networks:
      - c2ng
    depends_on:
      - mongo
      - influxdb
      - oauth
      - uss

  c2ng-ua:
    image: c2ng-uas-sim
    env_file:
      - .env
    volumes:
      - ./c2ng/common:/app/c2ng/common
      - ./c2ng/uas_sim:/app/c2ng/uas_sim
    ports:
      - 9092:9092/udp
    networks:
      - c2ng
    depends_on:
      - c2ng
    profiles:
      - noautostart

networks:
  c2ng:

volumes:
  influx:
