service:
  port: 9090
logging:
  verbose: false
oauth:
  keycloak:
    base: http://oauth:8080
    realm: c2ng
    retry-timeout: 5
uss:
  endpoint: http://uss:9091
  oauth:
    keycloak:
      base: http://oauth:8080
      realm: c2ng
      auth-client-id: uss-access
mongo:
  uri: mongodb://root:example@mongo:27017/
sliceman:
  provider: simulated
  simulated:
    ue: 127.0.0.1
    adx: 127.0.0.1
    gateway: 127.0.0.1
  cumucore:
    uri: https://host:port/
security:
  certificate: /app/config/c2ng/service.pem
  private: /app/config/c2ng/private.pem
  default-ttl: 3600
influx:
  uri: http://influxdb:8086
  org: c2ng
  bucket: aerial-data
