service:
  port: 9090
logging:
  verbose: false
uss:
  endpoint: http://host.docker.internal:9091
mongo:
  uri: mongodb://root:example@mongo:27017/
nsacf:
  simulated: true
security:
  certificate: /c2ng/config/service.pem
