service:
  port: 9090
logging:
  verbose: false
uss:
  endpoint: http://host.docker.internal:9091
mongo:
  uri: mongodb://root:example@mongo:27017/
nsacf:
  simulated: true
security:
  certificate: /c2ng/config/service.pem
  private: /c2ng/config/private.pem
  default-ttl: 3600
keycloak:
  base: http://host.docker.internal:8080
  realm: c2ng
