openapi: 3.0.2
info:
  description: Documentation for the Command-and-Control NextGen API
  title: C2NG API Definition
  version: 1.0.0
components:
  schemas:
    AddressRequestResponse:
      properties:
        Address:
          description: IP Address for the peer
        Success:
          description: Success flag
          enum:
          - true
          type: boolean
      required:
      - Address
      type: object
    AddressRequestResponseErrors:
      properties:
        Segment:
          enum:
          - invalid
          type: string
        Session:
          enum:
          - session_not_found
          - peer_not_connected
          type: string
        UasID:
          enum:
          - not_found
          type: string
      type: object
    AddressRequestResponseFailed:
      properties:
        Errors:
          $ref: '#/components/schemas/AddressRequestResponseErrors'
        Success:
          description: Failure flag.
          enum:
          - false
          type: boolean
      required:
      - Errors
      type: object
    AerialConnectionSessionRequest:
      properties:
        IMSI:
          description: UE IMSI ID
          type: string
        Metadata:
          description: Opaque object to pass to USSP
          type: object
        ReferenceTime:
          description: UNIX Timestamp
          type: number
        Segment:
          description: 'Segment for which to request a session: airborne (''ua'')
            or ground (''adx'').'
          enum:
          - ua
          - adx
          type: string
        UasID:
          description: CAA UAS ID
          type: string
      required:
      - ReferenceTime
      - Segment
      - UasID
      type: object
    AerialConnectionSessionResponse:
      properties:
        EncryptedPrivateKey:
          description: Session private key encrypted with client secret
          type: string
        GatewayIP:
          description: Gateway IP for aerial connection.
        IP:
          description: Own IP address for aerial connection.
        KID:
          description: Key unique identifier
          type: string
        Success:
          description: Success flag
          enum:
          - true
          type: boolean
      required:
      - EncryptedPrivateKey
      - GatewayIP
      - IP
      - KID
      type: object
    AerialConnectionSessionResponseErrors:
      properties:
        Request:
          enum:
          - imsi_required
          type: string
        USS:
          enum:
          - provider_unavailable
          - flight_not_approved
          type: string
      type: object
    AerialConnectionSessionResponseFailed:
      properties:
        Errors:
          $ref: '#/components/schemas/AerialConnectionSessionResponseErrors'
        Success:
          description: Failure flag.
          enum:
          - false
          type: boolean
      required:
      - Errors
      type: object
    BaseSuccess:
      properties:
        Success:
          description: Success flag
          enum:
          - true
          type: boolean
      type: object
    CertificateRequestResponse:
      properties:
        Certificate:
          description: Certificate with a public key as a PEM string
          type: string
        KID:
          description: Key unique identifier
          type: string
        Success:
          description: Success flag
          enum:
          - true
          type: boolean
      required:
      - Certificate
      - KID
      type: object
    CertificateRequestResponseErrors:
      properties:
        Segment:
          enum:
          - invalid
          type: string
        Session:
          enum:
          - session_not_found
          - peer_not_connected
          type: string
        UasID:
          enum:
          - not_found
          type: string
      type: object
    CertificateRequestResponseFailed:
      properties:
        Errors:
          $ref: '#/components/schemas/CertificateRequestResponseErrors'
        Success:
          description: Failure flag.
          enum:
          - false
          type: boolean
      required:
      - Errors
      type: object
    GeoPointWGS84:
      properties:
        Altitude:
          description: Geodetic altitude in meters
          type: number
        Latitude:
          description: Latitude in degress
          type: number
        Longitude:
          description: Longitude in degress
          type: number
      required:
      - Altitude
      - Latitude
      - Longitude
      type: object
    SignalStatsReportRequest:
      properties:
        Baro:
          description: Aircraft Barometric Altitude
          type: number
        Cell:
          description: Aircraft Serving physical cell identifier
          type: string
        FrequencyBand:
          description: Aircraft Serving Frequency Band Identification
          type: string
        Heading:
          description: Aircraft True Heading (degrees)
          type: number
        HeartbeatLoss:
          description: Heartbeat Loss Flag
          type: boolean
        Pitch:
          description: Aircraft Pitch (degrees)
          type: integer
        RSRP:
          description: Reference Signal Received Power
          type: integer
        RSRQ:
          description: Reference Signal Received Quality
          type: integer
        RSSI:
          description: Received Signal Strength Indicator
          type: integer
        RTT:
          description: Round-Trip Time (ms)
          type: integer
        Radio:
          description: Current radio access mode
          enum:
          - 4glte
          - 5gnr
          type: string
        ReferenceTime:
          description: UNIX Timestamp
          type: number
        Roll:
          description: Aircraft Roll (degrees)
          type: integer
        SINR:
          description: Signal to Interference & Noise Ratio
          type: integer
        UasID:
          type: string
        VAir:
          description: Aircraft Air Speed (meters per second)
          type: number
        VDown:
          description: Aircraft Downward Velocity (meters per second)
          type: number
        VEast:
          description: Aircraft Eest Velocity (meters per second)
          type: number
        VNorth:
          description: Aircraft North Velocity (meters per second)
          type: number
        Waypoint:
          allOf:
          - $ref: '#/components/schemas/GeoPointWGS84'
          description: Reference Position
        Yaw:
          description: Aircraft Yaw (degrees)
          type: integer
      required:
      - HeartbeatLoss
      - RSRP
      - Radio
      - ReferenceTime
      - UasID
      - Waypoint
      type: object
    ValidationError:
      properties:
        Errors:
          additionalProperties:
            items:
              type: string
            type: array
          description: Error identifier dict
          type: object
        Success:
          description: Failure flag.
          enum:
          - false
          type: boolean
      type: object
paths:
  /address/{uasid}/{segment}:
    get:
      parameters:
      - description: UAS ID for which to fetch the peer's address.
        in: path
        name: UasID
        required: true
        schema:
          type: string
      - description: Segment for which to fetch the peer's certificate
        in: path
        name: Segment
        required: true
        schema:
          enum:
          - ua
          - adx
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressRequestResponse'
          description: Success payload containing peer's address
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressRequestResponseFailed'
          description: Payload containing error description
      summary: Request a current address from existing connectivity session.
  /certificate/{uasid}/{segment}:
    get:
      parameters:
      - description: UAS ID for which to fetch the peer's certificate
        in: path
        name: UasID
        required: true
        schema:
          type: string
      - description: Segment for which to fetch the peer's certificate
        in: path
        name: Segment
        required: true
        schema:
          enum:
          - ua
          - adx
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateRequestResponse'
          description: Success payload containing peer's certificate
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateRequestResponseFailed'
          description: Payload containing error description
      summary: Request a current certificate from existing connectivity session.
  /session:
    delete:
      parameters:
      - description: UAS ID for the session
        in: path
        name: UasID
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseSuccess'
          description: Success payload containing session information
      summary: Request a new session for an ADX client (RPS or USS services)
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AerialConnectionSessionRequest'
        description: Connectivity Session Request
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AerialConnectionSessionResponse'
          description: Success payload containing session information
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AerialConnectionSessionResponseFailed'
          description: Payload containing error description
      summary: Request a new session for an ADX client (RPS or USS services)
  /signal:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignalStatsReportRequest'
        description: A measurement sample object.
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseSuccess'
          description: Sample is successfully received.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: Payload containing error description.
      summary: Receives a sample of signal measurements from a UA with reference time
        and position.
