openapi: 3.0.2
info:
  description: Documentation for the Command-and-Control NextGen API
  title: C2NG API Definition
  version: 1.0.0
components:
  schemas:
    AdxConnectionSessionRequest:
      properties:
        ReferenceTime:
          description: UNIX Timestamp
          type: integer
        UasID:
          type: string
      required:
      - ReferenceTime
      type: object
    AdxConnectionSessionResponse:
      properties:
        EncryptedPrivateKey:
          description: Session private key encrypted with client secret
          type: string
        GatewayIP:
          description: Gateway IP for ADX connection.
        IP:
          description: Own IP address for the ADX connection.
        Success:
          description: Success flag
          enum:
          - true
          type: boolean
      required:
      - EncryptedPrivateKey
      - GatewayIP
      - IP
      type: object
    AdxConnectionSessionResponseErrors:
      properties:
        USS:
          enum:
          - here_define_the_errors
          type: string
      required:
      - USS
      type: object
    AdxConnectionSessionResponseFailed:
      properties:
        Errors:
          $ref: '#/components/schemas/AdxConnectionSessionResponseErrors'
        Message:
          type: string
        Success:
          description: Failure flag.
          enum:
          - false
          type: boolean
      required:
      - Errors
      type: object
    AerialConnectionSessionRequest:
      properties:
        IMSI:
          description: UE IMSI ID
          type: string
        Metadata:
          description: Opaque object to pass to USSP
          type: object
        ReferenceTime:
          description: UNIX Timestamp
          type: integer
        UasID:
          description: CAA UAS ID
          type: string
      required:
      - IMSI
      - ReferenceTime
      - UasID
      type: object
    AerialConnectionSessionResponse:
      properties:
        EncryptedPrivateKey:
          description: Session private key encrypted with client secret
          type: string
        GatewayIP:
          description: Gateway IP for aerial connection.
        IP:
          description: Own IP address for aerial connection.
        Success:
          description: Success flag
          enum:
          - true
          type: boolean
      required:
      - EncryptedPrivateKey
      - GatewayIP
      - IP
      type: object
    AerialConnectionSessionResponseErrors:
      properties:
        USS:
          enum:
          - provider_unavailable
          - flight_not_approved
          type: string
      required:
      - USS
      type: object
    AerialConnectionSessionResponseFailed:
      properties:
        Errors:
          $ref: '#/components/schemas/AerialConnectionSessionResponseErrors'
        Message:
          type: string
        Success:
          description: Failure flag.
          enum:
          - false
          type: boolean
      required:
      - Errors
      type: object
    CertificateRequestResponse:
      properties:
        Certificate:
          description: Certificate with a public key as a PEM string
          type: string
        Success:
          description: Success flag
          enum:
          - true
          type: boolean
      required:
      - Certificate
      type: object
    CertificateRequestResponseErrors:
      properties:
        Session:
          enum:
          - session_not_found
          - peer_not_connected
          type: string
        UasID:
          enum:
          - not_found
          type: string
      type: object
    CertificateRequestResponseFailed:
      properties:
        Errors:
          $ref: '#/components/schemas/CertificateRequestResponseErrors'
        Message:
          type: string
        Success:
          description: Failure flag.
          enum:
          - false
          type: boolean
      required:
      - Errors
      type: object
paths:
  /adx/session:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdxConnectionSessionRequest'
        description: ADX Connectivity Session Request
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdxConnectionSessionResponse'
          description: Success payload containing session information
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdxConnectionSessionResponseFailed'
          description: Payload containing error description
      summary: Request a new session for an ADX client (RPS or USS services)
  /certificate/adx/{uasid}:
    get:
      parameters:
      - description: UAS ID for which to fetch the peer's certificate
        in: path
        name: UasID
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateRequestResponse'
          description: Success payload containing peer's certificate
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateRequestResponseFailed'
          description: Payload containing error description
      summary: Request a new session for an ADX client (RPS or USS services)
  /certificate/ua/{uasid}:
    get:
      parameters:
      - description: UAS ID for which to fetch the peer's certificate
        in: path
        name: UasID
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateRequestResponse'
          description: Success payload containing peer's certificate
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertificateRequestResponseFailed'
          description: Payload containing error description
      summary: Request a new session for an ADX client (RPS or USS services)
  /ua/session:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AerialConnectionSessionRequest'
        description: Aerial Connectivity Session Request
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AerialConnectionSessionResponse'
          description: Success payload containing session information
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AerialConnectionSessionResponseFailed'
          description: Payload containing error description
      summary: Request a new session for UA
